# Generated by Django 4.2.14 on 2024-09-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_destination', models.CharField(default='none', max_length=100)),
                ('kms', models.IntegerField(default='none')),
                ('duration', models.DurationField(default='none')),
                ('toll_fare', models.IntegerField(blank=True, null=True)),
                ('parking_fare', models.IntegerField(blank=True, null=True)),
                ('ride_fare', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('online', 'online'), ('cash', 'cash'), ('wallet', 'wallet')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_at', models.TimeField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, default=30, max_digits=10, null=True)),
                ('ride_status', models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('declined', 'declined'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('Started', 'Started'), ('completed', 'completed')], default=('pending', 'pending'), max_length=20)),
                ('Front_pic', models.ImageField(blank=True, default=None, null=True, upload_to='ride_images')),
                ('Back_pic', models.ImageField(blank=True, default=None, null=True, upload_to='ride_images')),
                ('selfie', models.ImageField(blank=True, default=None, null=True, upload_to='ride_images')),
                ('opening_kms_screen', models.ImageField(blank=True, default=None, null=True, upload_to='ride_images')),
                ('closing_kms_screen', models.ImageField(blank=True, default=None, null=True, upload_to='ride_images')),
                ('is_extra', models.BooleanField(default=False)),
                ('extra_img', models.ImageField(blank=True, default=None, null=True, upload_to='ride_images')),
            ],
        ),
    ]
