# Generated by Django 4.2.14 on 2024-07-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('kms', models.IntegerField()),
                ('Fare', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_at', models.TimeField()),
                ('ride_status', models.CharField(choices=[('cancelled', 'cancelled'), ('Started', 'Started'), ('completed', 'completed')], max_length=20)),
                ('ride_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timing', models.TimeField()),
                ('Front_pic', models.BinaryField()),
                ('Back_pic', models.BinaryField()),
                ('selfie', models.BinaryField()),
            ],
        ),
    ]
