# Generated by Django 5.1 on 2024-08-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('Started', 'Started'), ('completed', 'completed')], default=('pending', 'pending'), max_length=20),
        ),
    ]
