# Generated by Django 4.2.14 on 2024-07-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendorApp', '0002_cartype_route_car'),
        ('customerApp', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='Car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorApp.car'),
        ),
        migrations.AddField(
            model_name='ride',
            name='Extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerApp.extra'),
        ),
        migrations.AddField(
            model_name='ride',
            name='costomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.account'),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorApp.driver'),
        ),
        migrations.AddField(
            model_name='ride',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorApp.route'),
        ),
        migrations.AddField(
            model_name='extra',
            name='Route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorApp.route'),
        ),
    ]
