# Generated by Django 4.2.14 on 2024-08-02 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0002_rename_costomer_ride_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
