# Generated by Django 5.1 on 2024-08-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('confirmed', 'confirmed'), ('assigned', 'assigned'), ('cancelled', 'cancelled'), ('Started', 'Started'), ('completed', 'completed')], default=('pending', 'pending'), max_length=20),
        ),
    ]
