# Generated by Django 5.1 on 2024-08-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='extra_img',
        ),
        migrations.AddField(
            model_name='ride',
            name='extra_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ride_images'),
        ),
    ]
