# Generated by Django 5.1 on 2024-08-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0002_alter_ride_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('declined', 'declined'), ('cancelled', 'cancelled'), ('Started', 'Started'), ('completed', 'completed')], default=('pending', 'pending'), max_length=20),
        ),
    ]
