# Generated by Django 5.1 on 2024-08-28 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
