# Generated by Django 5.1 on 2024-08-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0003_alter_ride_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='closing_kms_input',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='opening_kms_input',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
