# Generated by Django 5.1 on 2024-08-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0003_alter_ride_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
