# Generated by Django 5.1 on 2024-08-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0003_alter_ride_payment_status_alter_ride_vender_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='vender_id',
            new_name='vendor_id',
        ),
    ]
