# Generated by Django 4.2.14 on 2024-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0003_ride_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='fare',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extra',
            name='parking_fare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extra',
            name='toll_fare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
