# Generated by Django 5.1 on 2024-08-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0003_remove_extra_extra_img_ride_extra_img'),
        ('vendorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendorApp.car'),
            preserve_default=False,
        ),
    ]
