# Generated by Django 5.1 on 2024-08-16 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0004_ride_car'),
        ('vendorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendorApp.car'),
        ),
    ]
