# Generated by Django 4.2.14 on 2024-08-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0004_extra_fare_alter_extra_parking_fare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='fare',
        ),
    ]
