# Generated by Django 5.1 on 2024-08-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0005_alter_ride_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='payment_type',
            field=models.CharField(choices=[('online', 'online'), ('cash', 'cash'), ('wallet', 'wallet')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
