# Generated by Django 5.1 on 2024-08-17 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0006_extra_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='all_include_fare',
            new_name='ride_fare',
        ),
    ]
