# Generated by Django 4.2.14 on 2024-08-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0006_extra_new_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='new_destination',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
