# Generated by Django 4.2.14 on 2024-07-29 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('licence', models.BinaryField()),
                ('aadhar_card', models.BinaryField()),
                ('join_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('otp', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc', to='usersApp.account')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.account')),
            ],
        ),
    ]
