# Generated by Django 4.2.14 on 2024-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='drop_location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='pickup_location',
            field=models.CharField(max_length=1000),
        ),
    ]
