# Generated by Django 4.2.14 on 2024-07-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
        ('vendorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_model', models.CharField(verbose_name=50)),
                ('Car_brand', models.CharField(verbose_name=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('oneway', 'oneway'), ('roundtrip', 'roundtrip'), ('local', 'local'), ('airport_pickup', 'airport_pickup'), ('airport_drop', 'airport_drop')], max_length=20)),
                ('pickup_location', models.CharField(max_length=150)),
                ('drop_location', models.CharField(max_length=150)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Duration', models.DurationField()),
                ('kms', models.IntegerField()),
                ('Car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorApp.cartype')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MFG_Year', models.DateField()),
                ('Front_pic', models.BinaryField()),
                ('Back_pic', models.BinaryField()),
                ('Registration_Number', models.CharField(max_length=20)),
                ('rc_photo', models.BinaryField()),
                ('area', models.CharField(verbose_name=20)),
                ('available', models.BooleanField()),
                ('Car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorApp.cartype')),
                ('Vender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.account')),
            ],
        ),
    ]
