# Generated by Django 4.2.14 on 2024-08-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='drop_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.CharField(choices=[('none', 'none'), ('4 hrs 40 km', '4 hrs 40 km'), ('8 hrs 80 km', '8 hrs 80 km'), ('12 hrs 120 km', '12 hrs 120 km')], default=('none', 'none'), max_length=50),
        ),
        migrations.AlterField(
            model_name='route',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, default=30, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='kms',
            field=models.IntegerField(default=1),
        ),
    ]
