# Generated by Django 5.1 on 2024-08-30 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0004_rename_vender_id_ride_vendor_id'),
        ('paymentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='advance_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='advance_payment_percent',
            field=models.CharField(blank=True, choices=[('25', '25'), ('50', '50')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='advance_payment_type',
            field=models.CharField(blank=True, choices=[('Wallet', 'Wallet'), ('credit', 'credit'), ('debit', 'debit')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('paid', 'paid')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pending_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pending_paymeny_Type',
            field=models.CharField(blank=True, choices=[('online', 'online'), ('cash', 'cash'), ('wallet', 'wallet')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerApp.ride'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
