# Generated by Django 4.2.14 on 2024-08-04 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='advance_payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='pending_payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
