# Generated by Django 5.1 on 2024-09-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0002_alter_payment_advance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pending_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
