# Generated by Django 5.1 on 2024-09-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0003_payment_pending_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='advance_payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='advance_razorpay_payment_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pending_payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pending_razorpay_payment_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
