# Generated by Django 5.1 on 2024-09-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0004_remove_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pending_paymeny_Type',
            field=models.CharField(blank=True, choices=[('upi', 'upi'), ('cash', 'cash'), ('wallet', 'wallet'), ('card', 'card'), ('netbanking', 'netbanking')], max_length=20, null=True),
        ),
    ]
