# Generated by Django 4.2.14 on 2024-08-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='OTP_verification',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
