# Generated by Django 4.2.14 on 2024-08-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('Vendor', 'Vendor'), ('Admin', 'Admin'), ('Driver', 'Driver'), ('Customer', 'Customer')], default='Vendor', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
