# Generated by Django 4.2.14 on 2024-08-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_alter_account_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('Vendor', 'Vendor'), ('Admin', 'Admin'), ('Driver', 'Driver'), ('Customer', 'Customer')], max_length=255),
        ),
    ]
