# Generated by Django 4.2.14 on 2024-08-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0004_alter_account_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(null=True),
        ),
    ]
