# Generated by Django 4.2.14 on 2024-08-12 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0007_account_groups_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='works_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
