# Generated by Django 4.2.14 on 2024-08-12 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0009_alter_accountdetail_works_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='works_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksFor', to=settings.AUTH_USER_MODEL),
        ),
    ]
