# Generated by Django 4.2.14 on 2024-08-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0010_alter_accountdetail_works_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
